# Generated by Django 2.2.2 on 2019-07-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_TESTING', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_endpoint', models.CharField(max_length=100)),
                ('request_method', models.CharField(choices=[['GET', 'GET'], ['POST', 'POST'], ['PUT', 'PUT'], ['DELETE', 'DELETE']], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Query_params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1024)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_TESTING.Environment')),
            ],
        ),
    ]
