# Generated by Django 2.2.2 on 2019-06-25 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('driver_file', models.FileField(upload_to='files/driver')),
                ('description', models.CharField(max_length=256)),
                ('browser', models.CharField(choices=[['chrome', 'Chrome'], ['ie', 'Internet Explorer'], ['firefox', 'Firefox']], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relative_path', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[['local', 'Local'], ['dev', 'Development'], ['qa', 'QA'], ['stage', 'Staging'], ['prod', 'Production']], max_length=10)),
                ('base_url', models.URLField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('by', models.CharField(choices=[['id', 'By ID'], ['class', 'By Class'], ['xpath', 'By Xpath'], ['name', 'By Name']], max_length=100)),
                ('value', models.CharField(max_length=1024)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1024)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Environment')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Page')),
            ],
        ),
    ]
