# Generated by Django 2.2.2 on 2019-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='by',
            field=models.CharField(choices=[['id', 'By ID'], ['class', 'By Class'], ['xpath', 'By Xpath'], ['name', 'By Name'], ['css_selector', 'Css Selector']], max_length=100),
        ),
    ]
